!TO         "mcfont-64x", CBM
!SYMBOLLIST "mcfont.sym"

!SOURCE     "const.inc"
!SOURCE     "macro.inc"

ADDR_MCFONT = ADDR_MAIN
SIZE_MCFONT = SIZE_MAIN

* = ADDR_MCFONT

stash_mcfont:

            +STASHI mcfont_data, REU_ADDR_MCFONT, REU_SIZE_MCFONT
            RTS

!MACRO undefined_character {
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........
}

mcfont_data:

;;; commercial at
  +undefined_character

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %######..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %####....
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %####....
  !BYTE %........

  !BYTE %######..
  !BYTE %##......
  !BYTE %##......
  !BYTE %####....
  !BYTE %##......
  !BYTE %##......
  !BYTE %######..
  !BYTE %........

  !BYTE %######..
  !BYTE %##......
  !BYTE %##......
  !BYTE %####....
  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##......
  !BYTE %######..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %######..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %######..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %######..
  !BYTE %........

  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %####....
  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %######..
  !BYTE %........

  !BYTE %##..##..
  !BYTE %######..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %##......
  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %####....
  !BYTE %##......
  !BYTE %##......
  !BYTE %##......
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..####..
  !BYTE %........

  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##......
  !BYTE %..##....
  !BYTE %....##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %######..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %######..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %........

  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........

  !BYTE %######..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %..##....
  !BYTE %##......
  !BYTE %##......
  !BYTE %######..
  !BYTE %........

mini_char_set_LEFT_SQUARE_BRACKET:
  !BYTE %..####..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..####..
  !BYTE %........

;;; british pound
  +undefined_character

mini_char_set_RIGHT_SQUARE_BRACKET:
  !BYTE %..####..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %..####..
  !BYTE %........

;;; up arrow
  +undefined_character

;;; left arrow
  +undefined_character

  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........

  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........
  !BYTE %..##....
  !BYTE %........

;;; quotation mark
  +undefined_character

;;; pound sign
  +undefined_character

;;; dollar sign
  +undefined_character

;;; percent sign
  +undefined_character

;;; ampersand
  +undefined_character

  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........

  !BYTE %....##..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %....##..
  !BYTE %........

  !BYTE %..##....
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %..##....
  !BYTE %........

;;; asterisk
  +undefined_character

;;; plus
  +undefined_character

  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %##......

  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %######..
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........

  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........

  !BYTE %....##..
  !BYTE %....##..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %##......
  !BYTE %##......
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %..##....
  !BYTE %####....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %######..
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %....##..
  !BYTE %..##....
  !BYTE %##......
  !BYTE %##......
  !BYTE %######..
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %....##..
  !BYTE %..##....
  !BYTE %....##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %....##..
  !BYTE %..####..
  !BYTE %##..##..
  !BYTE %######..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %........

  !BYTE %######..
  !BYTE %##......
  !BYTE %##......
  !BYTE %..##....
  !BYTE %....##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %..####..
  !BYTE %##......
  !BYTE %##......
  !BYTE %####....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %######..
  !BYTE %....##..
  !BYTE %....##..
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %##......
  !BYTE %##......
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %..##....
  !BYTE %##..##..
  !BYTE %##..##..
  !BYTE %..####..
  !BYTE %....##..
  !BYTE %##..##..
  !BYTE %..##....
  !BYTE %........

  !BYTE %........
  !BYTE %........
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........

  !BYTE %........
  !BYTE %........
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %........
  !BYTE %..##....
  !BYTE %..##....
  !BYTE %##......

;;; less than
  +undefined_character

;;; equal
  +undefined_character

;;; greater than
  +undefined_character

;;; question mark
  +undefined_character

  !BYTE %........
  !BYTE %........
  !BYTE %########
  !BYTE %########
  !BYTE %########
  !BYTE %########
  !BYTE %........
  !BYTE %........

  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character

;mini_char_set_UPPER_RIGHT_CURVE:
  !BYTE %........
  !BYTE %........
  !BYTE %##......
  !BYTE %####....
  !BYTE %######..
  !BYTE %######..
  !BYTE %..####..
  !BYTE %..####..

;mini_char_set_LOWER_LEFT_CURVE:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..######
  !BYTE %..######
  !BYTE %....####
  !BYTE %......##
  !BYTE %........
  !BYTE %........

;mini_char_set_LOWER_RIGHT_CURVE:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %######..
  !BYTE %######..
  !BYTE %####....
  !BYTE %##......
  !BYTE %........
  !BYTE %........

  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character

;mini_char_set_UPPER_LEFT_CURVE:
  !BYTE %........
  !BYTE %........
  !BYTE %......##
  !BYTE %....####
  !BYTE %..######
  !BYTE %..######
  !BYTE %..####..
  !BYTE %..####..

  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character

;mini_char_set_HORIZONTAL_VERTICAL_CROSS:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %########
  !BYTE %########
  !BYTE %########
  !BYTE %########
  !BYTE %..####..
  !BYTE %..####..

  +undefined_character

;mini_char_set_VERTICAL_LINE:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..####..

  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character

;mini_char_set_VERTICAL_LINE_T_RIGHT:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..######
  !BYTE %..######
  !BYTE %..######
  !BYTE %..######
  !BYTE %..####..
  !BYTE %..####..

  +undefined_character

;mini_char_set_LOWER_LEFT_CORNER:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %..######
  !BYTE %..######
  !BYTE %..######
  !BYTE %..######
  !BYTE %........
  !BYTE %........

;mini_char_set_UPPER_RIGHT_CORNER:
  !BYTE %........
  !BYTE %........
  !BYTE %######..
  !BYTE %######..
  !BYTE %######..
  !BYTE %######..
  !BYTE %..####..
  !BYTE %..####..

  +undefined_character

;mini_char_set_UPPER_LEFT_CORNER:
  !BYTE %........
  !BYTE %........
  !BYTE %..######
  !BYTE %..######
  !BYTE %..######
  !BYTE %..######
  !BYTE %..####..
  !BYTE %..####..

;mini_char_set_HORIZONTAL_LINE_T_UP:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %########
  !BYTE %########
  !BYTE %########
  !BYTE %########
  !BYTE %........
  !BYTE %........

  +undefined_character

;mini_char_set_VERTICAL_LINE_T_LEFT:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %######..
  !BYTE %######..
  !BYTE %######..
  !BYTE %######..
  !BYTE %..####..
  !BYTE %..####..

  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character

;mini_char_set_LOWER_RIGHT_CORNER:
  !BYTE %..####..
  !BYTE %..####..
  !BYTE %######..
  !BYTE %######..
  !BYTE %######..
  !BYTE %######..
  !BYTE %........
  !BYTE %........

  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character
  +undefined_character

;mini_char_set_key_x_1:
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %...#.#.#
  !BYTE %..#.#.#.

;mini_char_set_key_x_2:
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %.#......
  !BYTE %#.......

;mini_char_set_key_1_3:
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#...
  !BYTE %..#.#...

;mini_char_set_key_1_4:
  !BYTE %#..#....
  !BYTE %#.#.....
  !BYTE %#.#..#..
  !BYTE %#.#.#...
  !BYTE %#.#.#..#
  !BYTE %..#.#..#
  !BYTE %....#..#
  !BYTE %....#..#

;mini_char_set_key_1_5:
  !BYTE %..#.....
  !BYTE %..#.....
  !BYTE %..#.....
  !BYTE %..#.#.#.
  !BYTE %..#.....
  !BYTE %..#.#.#.
  !BYTE %........
  !BYTE %........

;mini_char_set_key_1_6:
  !BYTE %.......#
  !BYTE %.......#
  !BYTE %.......#
  !BYTE %..#.#..#
  !BYTE %.......#
  !BYTE %#.#.#..#
  !BYTE %........
  !BYTE %........

;mini_char_set_key_x_1:
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %...#.#.#
  !BYTE %..#.#.#.

;mini_char_set_key_x_2:
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %.#......
  !BYTE %#.......

;mini_char_set_key_2_3:
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#...
  !BYTE %..#.....
  !BYTE %..#.....

;mini_char_set_key_2_4:
  !BYTE %#..#....
  !BYTE %#.#.....
  !BYTE %#.#..#..
  !BYTE %#.#.#...
  !BYTE %#.#.#..#
  !BYTE %#...#..#
  !BYTE %.......#
  !BYTE %.......#

;mini_char_set_key_2_5:
  !BYTE %..#.....
  !BYTE %..#.#...
  !BYTE %..#.#...
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %........
  !BYTE %........

;mini_char_set_key_2_6:
  !BYTE %.......#
  !BYTE %....#..#
  !BYTE %....#..#
  !BYTE %..#.#..#
  !BYTE %..#.#..#
  !BYTE %#.#.#..#
  !BYTE %........
  !BYTE %........

;mini_char_set_key_x_1:
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %...#.#.#
  !BYTE %..#.#.#.

;mini_char_set_key_x_2:
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %........
  !BYTE %.#......
  !BYTE %#.......

;mini_char_set_key_3_3:
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#.#.#.
  !BYTE %..#...#.
  !BYTE %..#...#.
  !BYTE %..#.#...
  !BYTE %..#.#.#.

;mini_char_set_key_3_4:
  !BYTE %#..#....
  !BYTE %#.#.....
  !BYTE %#.#..#..
  !BYTE %#.#.#...
  !BYTE %#.#....#
  !BYTE %#.#....#
  !BYTE %#...#..#
  !BYTE %..#.#..#

;mini_char_set_key_3_5:
  !BYTE %..#.....
  !BYTE %..#.#.#.
  !BYTE %..#.#...
  !BYTE %..#...#.
  !BYTE %..#...#.
  !BYTE %..#.#.#.
  !BYTE %........
  !BYTE %........

;mini_char_set_key_3_6:
  !BYTE %.......#
  !BYTE %..#.#..#
  !BYTE %#...#..#
  !BYTE %#.#....#
  !BYTE %#.#....#
  !BYTE %#.#.#..#
  !BYTE %........
  !BYTE %........

;mini_char_set_health_top_50:
  !BYTE %.##.....
  !BYTE %.##.....
  !BYTE %.##.....
  !BYTE %.##.....
  !BYTE %.##.....
  !BYTE %.##.....
  !BYTE %.##.....
  !BYTE %.##.....

;mini_char_set_health_top_100:
  !BYTE %.##..##.
  !BYTE %.##..##.
  !BYTE %.##..##.
  !BYTE %.##..##.
  !BYTE %.##..##.
  !BYTE %.##..##.
  !BYTE %.##..##.
  !BYTE %.##..##.

;mini_char_set_health_bot:
  !BYTE %..##..##
  !BYTE %..##..##
  !BYTE %..##..##
  !BYTE %########
  !BYTE %########
  !BYTE %........
  !BYTE %........
  !BYTE %........

!warn "MCFONT AVAILABLE: ", SIZE_MCFONT-(*-ADDR_MCFONT)

!if * > ADDR_MCFONT+SIZE_MCFONT {
  !serious "MCFONT TOO BIG"
}

